export const subjectsInfo = [
  {
    Title: "chemistry",
  },
  {
    Title: "biology",
  },
  {
    Title: "space",
  },
  {
    Title: "aeronautics",
  },
];

export const chemPageInfo = [
  {
    ChemSubject: "sucrose",
    ImgName: "Sucrose.jpg",
    Title: "Sucrose",
    ModelPath: "sucrose",
    ModelDetails: "SucrosDesc",
    QrCodeUrl:
      "https://storage.echoar.xyz/wispy-violet-4999/5d2d9243-5705-4acb-a040-fcea69386b7a",
    ARlink: "https://go.echoar.xyz/WYRA",
    ModelSize: "0.2",
  },
  {
    ChemSubject: "glucoside",
    ImgName: "octyl_glucoside.jpeg",
    Title: "Glucoside",
    ModelPath: "octyl_glucoside",
    ModelDetails: "GlucosideDesc",
    QrCodeUrl:
      "https://storage.echoar.xyz/wispy-violet-4999/5536ac9f-0daa-4643-a916-972fa31f166b",
    ARlink: "https://go.echoar.xyz/XvMY",
    ModelSize: "0.2",
  },
  {
    ChemSubject: "glucose",
    ImgName: "Glucose.jpg",
    Title: "Glucose",
    ModelPath: "glucose_molecule",
    ModelDetails: "GlucoseDesc",
    QrCodeUrl:
      "https://storage.echoar.xyz/wispy-violet-4999/5ce969cd-670d-4635-b131-1495ab10c521",
    ARlink: "https://go.echoar.xyz/2Rx9",
    ModelSize: "0.2",
  },
  {
    ChemSubject: "h2oMolecule",
    ImgName: "H2O.jpg",
    Title: "H2OMolecule",
    ModelPath: "h2o_molecule",
    ModelDetails: "H2OMoleculeDesc",
    QrCodeUrl:
      "https://storage.echoar.xyz/wispy-violet-4999/95fa00e3-8d8c-4e25-9143-a31944f68663",
    ARlink: "https://go.echoar.xyz/FwfR",
    ModelSize: "0.05",
  },
];

export const bioPageInfo = [
  {
    BioSubject: "animalCell",
    ImgName: "animal_cell.jpeg",
    Title: "AnimalCell",
    ModelPath: "simple_animal_cell_model",
    ModelDetails: "AnimalCellDesc",
    QrCodeUrl: "animalCell.png",
    ARlink: "https://go.echoar.xyz/iJmt",
    ModelSize: "0.02",
  },
  {
    BioSubject: "plantCell",
    ImgName: "plant_cell.jpeg",
    Title: "PlantCell",
    ModelPath: "plant_cell_-_cell_structure",
    ModelDetails: "PlantCellDesc",
    QrCodeUrl: "animalCell.png",
    ARlink: "https://go.echoar.xyz/iJmt",
    ModelSize: "0.01",
  },
  {
    BioSubject: "brain",
    ImgName: "humanBrain.jpeg",
    Title: "HumanBrain",
    ModelPath: "human_brain",
    ModelDetails: "HumanBrainDesc",
    QrCodeUrl: "animalCell.png",
    ARlink: "https://go.echoar.xyz/iJmt",
    ModelSize: "0.5",
  },
  {
    BioSubject: "spinal",
    ImgName: "segmentation_of_lungs_and_spinalColumn.jpeg",
    Title: "HumanLung",
    ModelPath: "segmentation_of_lungs_and_spinal_column",
    ModelDetails: "HumanLungDesc",
    QrCodeUrl: "animalCell.png",
    ARlink: "https://go.echoar.xyz/iJmt",
    ModelSize: "0.01",
  },
];

export const spacePageInfo = [
  {
    SpaceSubject: "spaceStation",
    ImgName: "spaceStationImg.jpg",
    Title: "InternationalSpaceStation",
    ModelPath: "SpaceStation",
    ModelDetails: "InternationalSpaceStationDesc",
    QrCodeUrl: "https://storage.echoar.xyz/wispy-violet-4999/5b70a60a-e496-4c68-a6e7-9f4d1f70bb14",
    ARlink: "https://go.echoar.xyz/i18a",
    ModelSize: "0.55",
  },
  {
    SpaceSubject: "spaceShuttle",
    ImgName: "DiscoverySpaceShuttleImg.jpg",
    Title: "SpaceShuttleDiscovery",
    ModelPath: "DiscoverySpaceShuttle",
    ModelDetails: "SpaceShuttleDiscoveryDesc",
    QrCodeUrl: "https://storage.echoar.xyz/wispy-violet-4999/828c5b27-e6ab-48c8-a9b7-07a810908dd5",
    ARlink: "https://go.echoar.xyz/uA3y",
    ModelSize: "0.1",
  },
  {
    SpaceSubject: "mercury",
    ImgName: "Mercury.svg",
    Title: "Mercury",
    ModelPath: "mercury_enhanced_color",
    ModelDetails: "MercuryDesc",
    QrCodeUrl:
      "https://storage.echoar.xyz/wispy-violet-4999/1ed8bbb4-536c-4616-afe9-0dbee6e3432c",
    ARlink: "https://go.echoar.xyz/3BB2",
    ModelSize: "0.5",
  },
  {
    SpaceSubject: "venus",
    ImgName: "Venus.svg",
    Title: "Venus",
    ModelPath: "venus",
    ModelDetails: "VenusDesc",
    QrCodeUrl: "https://storage.echoar.xyz/wispy-violet-4999/50a234a1-cc5c-4870-9e1d-d709a2f3d6d2",
    ARlink: "https://go.echoar.xyz/44Xn",
    ModelSize: "0.75",
  },
  {
    SpaceSubject: "earth",
    ImgName: "Earth.svg",
    Title: "Earth",
    ModelPath: "earth",
    ModelDetails: "EarthDesc",
    QrCodeUrl: "https://storage.echoar.xyz/wispy-violet-4999/90a2a92c-b69d-45d4-8935-9ea307faeb05",
    ARlink: "https://go.echoar.xyz/J8oi",
    ModelSize: "0.015",
  },
  {
    SpaceSubject: "mars",
    ImgName: "Mars.svg",
    Title: "Mars",
    ModelPath: "mars",
    ModelDetails: "MarsDesc",
    QrCodeUrl: "https://storage.echoar.xyz/wispy-violet-4999/633d6a9c-73d8-4207-ada6-61dc04cfebe3",
    ARlink: "https://go.echoar.xyz/rQke",
    ModelSize: "0.015",
  },
  {
    SpaceSubject: "jupiter",
    ImgName: "Jupiter.svg",
    Title: "Jupiter",
    ModelPath: "jupiter",
    ModelDetails: "JupiterDesc",
    QrCodeUrl: "https://storage.echoar.xyz/wispy-violet-4999/a89518a9-dc19-4857-89b0-7aea87236ecc",
    ARlink: "https://go.echoar.xyz/eG6s",
    ModelSize: "0.7",
  },
  {
    SpaceSubject: "saturn",
    ImgName: "Saturn.svg",
    Title: "Saturn",
    ModelPath: "saturn",
    ModelDetails: "SaturnDesc",
    QrCodeUrl: "https://storage.echoar.xyz/wispy-violet-4999/101dbcc9-b7a2-4e51-af71-7c73b2351e48",
    ARlink: "https://go.echoar.xyz/8oHR",
    ModelSize: "0.01",
  },
  {
    SpaceSubject: "uranus",
    ImgName: "Uranus.svg",
    Title: "Uranus",
    ModelPath: "uranus",
    ModelDetails: "UranusDesc",
    QrCodeUrl: "https://storage.echoar.xyz/wispy-violet-4999/ee979b82-19b0-4dad-b3d4-b4d07d1308a7",
    ARlink: "https://go.echoar.xyz/bttS",
    ModelSize: "0.7",
  },
  {
    SpaceSubject: "neptune",
    ImgName: "Neptune.svg",
    Title: "Neptune",
    ModelPath: "neptune",
    ModelDetails: "NeptuneDesc",
    QrCodeUrl: "https://storage.echoar.xyz/wispy-violet-4999/270df91e-d092-43b1-ad6c-b1835523ec15",
    ARlink: "https://go.echoar.xyz/ya76",
    ModelSize: "0.7",
  },
];

export const aerospaceInfo = [
  {
    URL: "dragon2",
    ImgName: "dragon2.jpeg",
    Title: "SpaceXDragon2",
  },
  {
    URL: "starship",
    ImgName: "starship.jpeg",
    Title: "SpaceXStarship",
  },
  {
    URL: "boeing757",
    ImgName: "boeing757.jpeg",
    Title: "Boeing757",
  },
  {
    URL: "boeing787",
    ImgName: "boeing787.jpg",
    Title: "Boeing787",
  },
  {
    URL: "ec135",
    ImgName: "EC135.jpeg",
    Title: "EurocopterEC135",
  },
];
